nanoframework/Samples

- Blinky/Blinky.sln
- Blinky/Blinky/Blinky.nfproj
- Blinky/Blinky/Blinky.sln
- Blinky/Blinky/Program.cs
- Blinky/Blinky/Properties/AssemblyInfo.cs
- Blinky/Blinky/packages.config
- DebugGC.Test/DebugGC.Test.sln
- DebugGC.Test/DebugGC.Test/DebugGC.Test.nfproj
- DebugGC.Test/DebugGC.Test/DebugGC.Test.nugetreferenceswitcher
- README.md
Signed-off-by: José Simões <jose.simoes@eclo.solutions>
> Add Solution with Blinky project

- HardwareEsp32/HardwareEsp32.nfproj
- HardwareEsp32/HardwareEsp32.sln
- HardwareEsp32/Program.cs
- HardwareEsp32/Properties/AssemblyInfo.cs
- HardwareEsp32/README.md
- HardwareEsp32/packages.config
- README.md
This sample show the use of the nanoframework.Hardware.Esp32 nuget package.
Changing the pins used by devices and access to the Esp32 Deep sleep functions.
> Added Hardware.Esp32 sample

- Converter.Base64/Base64Test.sln
- Converter.Base64/Base64Test/Base64Test.nfproj
- Converter.Base64/Base64Test/Program.cs
- Converter.Base64/Base64Test/Properties/AssemblyInfo.cs
- Converter.Base64/Base64Test/packages.config
- Converter.Base64/Base64TestingShared/Base64TestingShared.projitems
- Converter.Base64/Base64TestingShared/Base64TestingShared.shproj
- Converter.Base64/Base64TestingShared/TestCode.cs
- Converter.Base64/DesktopBase64Testing/App.config
- Converter.Base64/DesktopBase64Testing/DesktopBase64Testing.csproj
- Converter.Base64/DesktopBase64Testing/Program.cs
- Converter.Base64/DesktopBase64Testing/Properties/AssemblyInfo.cs
- Converter.Base64/README.Desktop.md
- Converter.Base64/README.md
- README.md
- Add VS solution with sample project.
- Update main README with link to sample.
> Add Base64 encode/decode sample

- README.md
- Resolves nanoframework/Home#456
> Fix links to some samples

- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore.sln
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/Configuration.cs
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/ConfigurationStore.cs
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore.nfproj
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/Program.cs
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/Properties/AssemblyInfo.cs
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/app.config
- samples/JsonConfigurationStore/JsonConfigurationStore/JsonConfigurationStore/packages.config
Add sample using nanoFramework.Json and Windows.Storage to persist a configuration json file on internal storage
Signed-off-by Andy Lyonette
> Add JsonConfigurationStore Sample

- samples/Blinky/Blinky/Program.cs
Verified and tested as of today. Had to look for a while, finally found the pin through Abstract.IO which helped a ton: https://github.com/steffalk/AbstractIO
> Added Netduino 3 Wifi onboard blue LED

- samples/Blinky/Blinky/Program.cs
sorted board types in comments, moving board name left for readability and added ULX3S pin def 
Signed-off-by:  gojimmypi
> Sort board types and add ULX3S to Blinky

- samples/Gpio/Gpio+Events/README.md
> Small typo in README

- samples/Graphics/Primitives/Primitives.nfproj
- samples/Graphics/Primitives/SimplePrimitives/RotateImage.cs
- samples/Graphics/Primitives/packages.config
> Update Primitives to latest assemblies

- samples/Graphics/Tetris/GameLogic/ByteMatrix.cs
- samples/Graphics/Tetris/GameLogic/GameBlocks.cs
- samples/Graphics/Tetris/GameLogic/GameUniverse.cs
- samples/Graphics/Tetris/GameLogic/HighScoreTable.cs
- samples/Graphics/Tetris/GpioButtonInputProvider.cs
- samples/Graphics/Tetris/NanoTetris.nfproj
- samples/Graphics/Tetris/Presentation/BlockBrushes.cs
- samples/Graphics/Tetris/Presentation/GradientStackPanel.cs
- samples/Graphics/Tetris/Presentation/NextBlockView.cs
- samples/Graphics/Tetris/Presentation/ScoreItem.cs
- samples/Graphics/Tetris/Presentation/StatisticsPanel.cs
- samples/Graphics/Tetris/Presentation/UniverseView.cs
- samples/Graphics/Tetris/Tetris.nfproj
- samples/Graphics/Tetris/TetrisApp.cs
- samples/Graphics/Tetris/packages.config
Fixes nuget location.
Applies some recommended code fixes.
Ensures sample works.
Ran on STM32F769I sucessfully (without buttons available). Reached the main menu sucessfully.
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
> Correct tetris sample

- samples/WiFiAP/Program.cs
- samples/WiFiAP/WiFiAP.nfproj
- samples/WiFiAP/WirelessAP.cs
- samples/WiFiAP/packages.config
- Fix issue reported on discord
- Updated and fixed typos in comments
- Updated references to latest
Using sample WiFiAP app
Signed-off-by: adriansoundy<adriansoundy@gmail.com>
> Set IP address on SoftAP and fix some typos

- samples/HTTP/HttpListener/HttpListener.nfproj
- samples/HTTP/HttpListener/packages.config
- samples/HTTP/HttpWebRequest/HttpWebRequest/HttpWebRequest.nfproj
- samples/HTTP/HttpWebRequest/HttpWebRequest/NetworkHelpers.cs
- samples/HTTP/HttpWebRequest/HttpWebRequest/Program.cs
- samples/HTTP/HttpWebRequest/HttpWebRequest/packages.config
Minor Update to HTTP.Samples
updated certificate protocol TLS1.2 to align with the global-root-ca site. updated date time set for the device the function had 2020 hard coded into the loop so it would run the function 30 times though it was not needed. 
sample did not function
tested on esp32
Signed-off-by: amgarnier<aaron.garnier@gmail.com>
> updated http

- samples/HTTP/HTTP.Samples.sln
- samples/HTTP/HttpAzureGET/HttpAzureGET.nfproj
- samples/HTTP/HttpAzureGET/NetworkHelpers.cs
- samples/HTTP/HttpAzureGET/Program.cs
- samples/HTTP/HttpAzureGET/Properties/AssemblyInfo.cs
- samples/HTTP/HttpAzureGET/README.md
- samples/HTTP/HttpAzureGET/SetPoint.cs
- samples/HTTP/HttpAzureGET/packages.config
- samples/HTTP/HttpAzurePOST/HttpAzurePOST.nfproj
- samples/HTTP/HttpAzurePOST/NetworkHelpers.cs
- samples/HTTP/HttpAzurePOST/Program.cs
- samples/HTTP/HttpAzurePOST/Properties/AssemblyInfo.cs
- samples/HTTP/HttpAzurePOST/README.md
- samples/HTTP/HttpAzurePOST/Temp.cs
- samples/HTTP/HttpAzurePOST/packages.config
- samples/HTTP/HttpWebRequest/HttpWebRequest/HttpWebRequest.nfproj
- samples/HTTP/HttpWebRequest/HttpWebRequest/packages.config
This is a sample which uses a POST http request to send temperature data (fake) from a device to Azure IOT Hub using a pem certificate.
Added a new project to Sample.Http for AzureIotHub POST
I wanted to show users how to use a POST http request on an embedded device with a certificate. To kill two birds with one stone I also integrated Azure Iot hub Api to send a HTTP post
Test on ESP32 wroom
Signed-off-by: amgarnier<aaron.garnier@gmail.com>
> HTTP Post to Azure IOT hub using pem certificate

- README.md
- samples/Logging/Logging.nfproj
- samples/Logging/Logging.sln
- samples/Logging/MyTestComponent.cs
- samples/Logging/Program.cs
- samples/Logging/Properties/AssemblyInfo.cs
- samples/Logging/README.md
- samples/Logging/app.config
- samples/Logging/packages.config
Adding nanoFramework.Logging samples
- Adding Adding nanoFramework.Logging samples for the new Logging platform
- Fixing the home page tables to be in pure Markdown
Samples are coming from the Tests https://github.com/nanoframework/nanoFramework.Logging/tree/develop/Tests/UnitTestDebugLogging
Signed-off-by: Ellerbach<laurelle@microsoft.com>
> Adding nanoFramework.Logging samples

- samples/WiFiAP/Program.cs
- samples/WiFiAP/WebServer.cs
- samples/WiFiAP/WiFiAP.nfproj
- samples/WiFiAP/Wireless80211.cs
- samples/WiFiAP/app.config
- samples/WiFiAP/packages.config
Fixing SoftAP with the new network helper.
- Find a way to fix the SoftAP example
- Tested with ESP32
Tested on ESP32 with different cases
Signed-off-by: Ellerbach <laurelle@microoft.com>
> Fixing SoftAP with new network helper

- samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Program.cs
- samples/MQTT/AwsMQTT/AwsMQTT/Program.cs
- samples/MQTT/AzureMQTT/AzureMQTT/Program.cs
- samples/MQTT/TestMqtt/Mosquito.TemperatureGauge/Program.cs
- samples/MQTT/TestMqtt/TestMqtt/Program.cs
Adjusting MQTT sample
- Adjusting MQTT sample following breaking changes in MQTT Client
Signed-off-by: Ellerbach <laurelle@microsoft.com>
> Adjusting MQTT sample

- samples/MQTT/AdvancedExample.Azure/Program.cs
This was broken by bot, as explained in nanoFramework/Home#819.
- Fixes nanoFramework/Home#827
Compiled on my PC.
> Fixing Azure MQTT sample

- README.md
- samples/Bluetooth/BluetoothLESerial/README.md
Add Readme to Bluetooth Sample
- Fixes/Closes/Resolves nanoFramework/Home#NNNN
> Add Readme to Bluetooth Sample 1

- samples/Networking/Socket.Client/Program.cs
- samples/Networking/Socket.Client/Socket.Client.nfproj
- samples/Networking/Socket.Client/packages.config
Update Network Client sample with latest NetworkHelper
Signed-off-by: adriansoundy <adriandoundy@gmail.comL>
> Update Network client sample

- samples/WebSockets/README.md
- samples/WebSockets/WebSockets.Client.Sample/README.md
- samples/WebSockets/WebSockets.Server.RgbSample/README.md
Added readmes
The more documentation the better
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
> Specific readme for websocket client and server sample

- samples/System.IO.FileSystem/BasicFileSystemExample/Program.cs
as per title
Signed-off-by: adriansoundy<adriansoudy@gmail.com>
> Reference Internal drive and improve comments

- samples/AMQP/Azure-IoT-Hub/Azure-IoT-Hub.nfproj
- samples/AMQP/Azure-IoT-Hub/packages.config
- samples/AMQP/Azure-ServiceBus-Sender/Azure-ServiceBus-Sender.nfproj
- samples/AMQP/Azure-ServiceBus-Sender/packages.config
- samples/CAN/Can.TestApp/Can.TestApp.nfproj
- samples/CAN/Can.TestApp/packages.config
- samples/Gpio/Gpio+EventsIoTStyle/packages.config
- samples/Graphics/Screens/m5stick-screen/packages.config
- samples/Graphics/SimpleWpf/packages.config
- samples/Graphics/Tetris/packages.config
- samples/Hardware.Esp32.Rmt/Ultrasonic/packages.config
- samples/Hardware.Esp32/packages.config
- samples/Hardware.Stm32/Stm32.PowerMode/Stm32.PowerMode.nfproj
- samples/Hardware.Stm32/Stm32.PowerMode/packages.config
- samples/Hardware.TI/TI.PowerMode/TI.PowerMode.nfproj
- samples/Hardware.TI/TI.PowerMode/packages.config
- samples/Timer/packages.config
- samples/WebSockets/WebSockets.Server.RgbSample/packages.config
- samples/Webserver/WebServer.Sample/packages.config
- samples/WiFiAP/packages.config
Brings S.DGpio nugets in sync.
Azure pipelines was still failing after last commit.
Pipeline run is sucessful against sln changes.
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
> Bring Gpio nugets up-to-date

- samples/Bluetooth/ImprovWifi/Improv.cs
- samples/Bluetooth/ImprovWifi/ImprovWifi.nfproj
- samples/Bluetooth/ImprovWifi/ImprovWifi.sln
- samples/Bluetooth/ImprovWifi/Program.cs
- samples/Bluetooth/ImprovWifi/Properties/AssemblyInfo.cs
- samples/Bluetooth/ImprovWifi/README.md
- samples/Bluetooth/ImprovWifi/packages.config
- samples/Bluetooth/README.md
Bluetooth sample for IMPROV Wifi provisioning 
> Improv bluetooth sample

- README.md
Update readme for Improv sample
> Update readme for Improv sample (English)

- samples/DependencyInjection/README.md
- samples/DependencyInjection/Simple/Program.cs
- samples/DependencyInjection/Simple/Properties/AssemblyInfo.cs
- samples/DependencyInjection/Simple/Simple.nfproj
- samples/DependencyInjection/Simple/Simple.sln
- samples/DependencyInjection/Simple/packages.config
- samples/DependencyInjection/SlowBlink/Application.cs
- samples/DependencyInjection/SlowBlink/Program.cs
- samples/DependencyInjection/SlowBlink/Properties/AssemblyInfo.cs
- samples/DependencyInjection/SlowBlink/Services/HardwareService.cs
- samples/DependencyInjection/SlowBlink/Services/IHardwareService.cs
- samples/DependencyInjection/SlowBlink/SlowBlink.nfproj
- samples/DependencyInjection/SlowBlink/SlowBlink.sln
- samples/DependencyInjection/SlowBlink/packages.config
- samples/DependencyInjection/category.txt
* Add dependency injection to sample repositories
Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>
> Add dependency injection sample

- samples/WiFiAP/Program.cs
- samples/WiFiAP/WiFiAP.nfproj
- samples/WiFiAP/WirelessAP.cs
- samples/WiFiAP/packages.config
Improve example by adding DHCP server.
- Tested on ESP32 and Android 12 phone
> Include DHCP server in WiFiAp sample

- samples/Bluetooth/BluetoothLESample1/BluetoothLESample1.nfproj
- samples/Bluetooth/BluetoothLESample1/Program.cs
- samples/Bluetooth/BluetoothLESample1/Properties/AssemblyInfo.cs
- samples/Bluetooth/BluetoothLESample1/packages.config
- samples/Bluetooth/BluetoothLESample2/BluetoothLESample2.nfproj
- samples/Bluetooth/BluetoothLESample2/Program.cs
- samples/Bluetooth/BluetoothLESample2/Properties/AssemblyInfo.cs
- samples/Bluetooth/BluetoothLESample2/packages.config
- samples/Bluetooth/BluetoothLESample3/BluetoothLESample3.nfproj
- samples/Bluetooth/BluetoothLESample3/Program.cs
- samples/Bluetooth/BluetoothLESample3/Properties/AssemblyInfo.cs
- samples/Bluetooth/BluetoothLESample3/packages.config
- samples/Bluetooth/BluetoothLESerial/BluetoothLESerial.nfproj
- samples/Bluetooth/BluetoothLESerial/Properties/AssemblyInfo.cs
- samples/Bluetooth/BluetoothLESerial/packages.config
- samples/Bluetooth/Central2/Central2.nfproj
- samples/Bluetooth/Central2/Program.cs
- samples/Bluetooth/Central2/packages.config
- samples/Bluetooth/ImprovWifi/ImprovWifi.nfproj
- samples/Bluetooth/ImprovWifi/Properties/AssemblyInfo.cs
- samples/Bluetooth/ImprovWifi/packages.config
- samples/Bluetooth/README.md
Updated Central2 to show scanning and connections
Updated other samples to reference new version
> Update bluetooth samples

- device-listing/Program.cs
- device-listing/device-listing.sln
- Add code to get executing path so it runs OK on AZDO pipeline.
- Migrate solution to VS2022.
- Fixes issue running tool on AZDO pipeline.
> Work on README composer

- device-listing/Configuration.json
- samples/UsbClient/README.md
- samples/UsbClient/UsbClient/UsbClient.sln
- samples/UsbClient/UsbClient/UsbStream/Program.cs
- samples/UsbClient/UsbClient/UsbStream/Properties/AssemblyInfo.cs
- samples/UsbClient/UsbClient/UsbStream/UsbStream.nfproj
- samples/UsbClient/UsbClient/UsbStream/packages.config
- samples/UsbClient/category.txt
> Add USB stream sample

- samples/System.IO.FileSystem/BasicFileSystemExample/BasicFileSystemExample.nfproj
Updating `<OutputType>`.
Set value of `<OutputType>` to `Exe`.
- Allows project to debug on connected device.
- Debugs on device.
> Fix output type for BasicFileSystemExample sample

- samples/Json/JsonConfigurationStore/ConfigurationStore.cs
- samples/Json/JsonConfigurationStore/Program.cs
> Fixing sample with Json configuration

- samples/Graphics/GenericDriver/GenericDriver.nfproj
- samples/Graphics/GenericDriver/GenericDriver.sln
- samples/Graphics/GenericDriver/Program.cs
- samples/Graphics/GenericDriver/Properties/AssemblyInfo.cs
- samples/Graphics/GenericDriver/README.md
- samples/Graphics/GenericDriver/category.txt
- samples/Graphics/GenericDriver/packages.config
- samples/Graphics/README.md
- samples/Graphics/UsingGenericDriver/Program.cs
- samples/Graphics/UsingGenericDriver/Properties/AssemblyInfo.cs
- samples/Graphics/UsingGenericDriver/README.md
- samples/Graphics/UsingGenericDriver/UsingGenericDriver.nfproj
- samples/Graphics/UsingGenericDriver/category.txt
- samples/Graphics/UsingGenericDriver/packages.config
Adding Generic Graphic Driver examples
- Adding Generic Graphic Driver examples
> Adding Generic Graphic Driver examples

- samples/Gpio/Esp32PulseCounter/Esp32PulseCounter.nfproj
- samples/Gpio/Esp32PulseCounter/Esp32PulseCounter.sln
- samples/Gpio/Esp32PulseCounter/Program.cs
- samples/Gpio/Esp32PulseCounter/Properties/AssemblyInfo.cs
- samples/Gpio/Esp32PulseCounter/README.md
- samples/Gpio/Esp32PulseCounter/category.txt
- samples/Gpio/Esp32PulseCounter/packages.config
- samples/Gpio/README.md
Adding Pulse Count samples for ESP32
-Adding Pulse Count samples for ESP32
Application used to test during the development phase
> Adding Pulse Count samples for ESP32

- samples/Graphics/Primitives/README.md
Added instructions for using icon fonts
> Added instructions for using icon fonts

- samples/MQTT/AdvancedExample.Aws/Program.cs
- samples/MQTT/AdvancedExample.Azure/Program.cs
- samples/MQTT/AdvancedExample.Certificates/Program.cs
- samples/MQTT/BasicExample.Ethernet/Program.cs
- samples/MQTT/BasicExample.WiFi/Program.cs
the build is currently failing because of other issues in the MQTT samples that are outdated.
It needs to be fixed on a separate PR before moving forward with this one.
https://github.com/nanoframework/Samples/pull/306#issuecomment-1614332703
> Fix Mqtt samples

- samples/Graphics/GenericDriver/GenericDriver.nfproj
- samples/Graphics/GenericDriver/packages.config
- samples/Graphics/UsingGenericDriver/Program.cs
- samples/Graphics/UsingGenericDriver/UsingGenericDriver.nfproj
- samples/Graphics/UsingGenericDriver/packages.config
Fixing sample for generic driver with old color utility class
- Fixing sample for generic driver with old color utility class
-
> Fixing sample for generic driver with old color utility class

- samples/1-Wire/README.md
- samples/AzureMQTTTwinsBMP280Sleep/README.md
- samples/AzureSDK/AzureEdgeOta/README.md
- samples/Collections/README.md
- samples/Gpio/Gpio+Events/README.md
- samples/Gpio/README.md
- samples/Graphics/README.md
- samples/HTTP/README.md
- samples/Hardware.Esp32.Rmt/README.md
- samples/Hardware.TI/README.md
- samples/Json/README.md
- samples/Logging/README.md
- samples/MQTT/README.md
- samples/Networking/README.md
- samples/SSL/README.md
- samples/UsbClient/README.md
- samples/WebSockets/README.md
- samples/WebSockets/README.zh-cn.md
- samples/WebSockets/WebSockets.Client.Sample/README.md
- samples/WebSockets/WebSockets.Client.Sample/README.zh-cn.md
- samples/WebSockets/WebSockets.Server.RgbSample/README.md
- samples/WebSockets/WebSockets.Server.RgbSample/README.zh-cn.md
- samples/WebSockets/Websockets.ServerClient.Sample/README.md
- samples/WebSockets/Websockets.ServerClient.Sample/README.zh-cn.md
I tested all the links in the readme files and if they didn't work, I replaced them with the valid links that were meant to be used
Contribution to maintain the quality of the samples
I went through the READMEs and clicked on the new links to see if they actually worked
> Fixed invalid links throughout the readme files

- samples/I2S/Output/I2sWavPlayer.cs
- samples/I2S/Output/Program.cs
- Adding comments related to troubleshooting low quality output
- Fixed issue with I2S bus 2 not working
- Save the next use time in troubleshooting
- On Device
> Adding comments related to troubleshooting low quality output

- samples/I2S/Output/I2sWavPlayer.cs
- samples/I2S/Output/Program.cs
- Renamed I2SWavPlayer to I2sWavPlayer
Resolves feedback in https://github.com/nanoframework/Samples/pull/325
- On Device
> Reverting class name change

- samples/Webserver/README.md
Fix few broken links in README
- Fix few broken links in README
> Fix few broken links in README

- samples/Bluetooth/ImprovWifi/Improv.cs
- samples/Bluetooth/ImprovWifi/ImprovWifi.nfproj
- samples/Bluetooth/ImprovWifi/README.md
Improve Improv-wifi
- As NetwokHelper only allows 1 setup, adjust the sample so it can work with multiple tries.
> Improve Improv-wifi

- samples/WiFiAP/Program.cs
- samples/WiFiAP/WebServer.cs
- samples/WiFiAP/WiFiAP.nfproj
- samples/WiFiAP/Wireless80211.cs
- samples/WiFiAP/WirelessAP.cs
- samples/WiFiAP/packages.config
Improving WiFi AP sample
- Works every time, including when freshy flashed device with all erased
- Make it also working even when the wifi helper has been used previously
On a real device
> Improving WiFi AP sample

- samples/Blinky/Blinky/Program.cs
Add support for AliExpress WROOM ESP32
> Add new LED config to blink sample

- samples/System.IO.FileSystem/BasicFileSystemExample/Program.cs
- samples/System.IO.FileSystem/MountExample/Program.cs
- Adjustment to new System.IO.FileSystem syntax
> Fix to match latest FileSystem syntax

- samples/System.IO.FileSystem/MountExample/Program.cs
- Shows use of the new CardDetectParameters class which gives a number of new options
-- Able to specify the level of the card detect pin
-- A new parameter to automatically mount SD card if card detect seen.
- A new parameter in SDCardSpiParameters & SDCardMmcParameters to specify card slot to allow multiple SD cards to be mounted with examples of creating multiple SDCard objects.
- Fixed the StorageEventManager.RemovableDeviceInserted/Removed events to show when drive was mounted not when card detected.
- Added CardDetectChanged event for Card Detct handling.
To match updates to System.FileSystem
Locally
> Update SDcard mount sample for latest update

- samples/System.IO.FileSystem/MountExample/Program.cs
Add example of configuring pins for SD cards on ESP32_S3 & ESP32-P4 devices.
> Add configure pins example to SD card sample

- samples/Beginner/ButtonNuget/README.md
- samples/Beginner/PwmLed/README.md
- samples/Beginner/ServoMotor/README.md
Fixing nit and missing file in Beginner content
- Fixing nit and missing file in Beginner content
> Fixing nit and missing file in Beginner content

- samples/Hosting/Logging/Program.cs
- samples/Hosting/Logging/Services/LoggingServices.cs
- samples/Hosting/SensorQueue/Program.cs
- samples/Hosting/SensorQueue/Services/DisplayService.cs
- samples/Hosting/SensorQueue/Services/MonitorService.cs
- samples/Hosting/SensorQueue/Services/SensorService.cs
- samples/Hosting/Simple/Program.cs
- samples/Hosting/SlowBlink/Program.cs
- samples/Hosting/SlowBlink/Services/LedService.cs
- Update signatures for Microsoft.Extensions.Hosting
- Fixes build
- Locally
> Fix hosting samples
